$D = "DialogShell Version $(tab) = $(sysinfo dsver)"
$W = "Windows version $(tab) = $(sysinfo winver)"
$X = "Temp directory $(tab) = $(env temp)"
$Y = "Windows directory $(tab) = $(windir)"
$Z = "System directory $(tab) = $(windir s)"
$V = "DOS path $(tab) = $(env path)"
$M = "Free memory $(tab) = $(sysinfo freemem)kb"
$S = "Screen width $(tab) = $(sysinfo screenwidth)"
$H = "Screen height $(tab) = $(sysinfo screenheight)"
$P = "Screen scale $(tab) = $(sysinfo scale)"
info "$D$(CR)$W$(CR)$X$(CR)$Y$(CR)$Z$(CR)$V$(CR)$M$(CR)$S$(CR)$H$(CR)$P" "System Information"